FROM alpine:3.21

RUN apk add --no-cache ca-certificates jq curl ffmpeg

ARG EXECUTABLE=./gomuks
COPY $EXECUTABLE /usr/bin/gomuks
VOLUME /data
WORKDIR /data
ENV GOMUKS_ROOT=/data

CMD ["/usr/bin/gomuks"]
