#!/bin/bash
mkdir -p deb/usr/bin/
mkdir -p target/
go build -o deb/usr/bin/gomuks
version=$(cat deb/DEBIAN/control | grep Version | awk '{ print $2 }')
dpkg-deb --build deb target/gomuks-$version.deb
